FROM    java:openjdk-8-jre-alpine

USER root
RUN mkdir /orientdb
RUN adduser -D -u %UID% -h /orientdb orientdb
RUN chown orientdb: /orientdb
RUN echo "orientdb:orientdb" | chpasswd

USER orientdb
WORKDIR /orientdb
ADD bin /orientdb/bin

USER root
RUN mkdir /data && mkdir /config && ln -s /data /orientdb/data && chown orientdb: /data 
RUN chown orientdb: /config -R && ln -s /config /orientdb/config

USER orientdb
VOLUME /data
VOLUME /config

USER orientdb
EXPOSE 9000
CMD %CMD% 
